import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Hero from '../sections/Hero'
import Countings from '../sections/Countings'
import Benefits from '../sections/Benefits'
import About from '../sections/About'
import About2 from '../sections/About2'
import Subscriptions from '../sections/Subscriptions'
import Mainlayout from '../layouts/mainlayout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Decentralized Voting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mainlayout>
      <Hero />
      <Countings />
      <Benefits />
      <About />
      <About2 />
      <Subscriptions />
      </Mainlayout>
    </>
  )
}
